import type { NextPage } from 'next';
import Head from 'next/head';
import { Contacts } from '../components/contacts/Contacts';
import Main from '../components/main/Main';
import MainBanner from '../components/mainBanner/MainBanner';
import MainContainer from '../components/UI/mainContainer/MainContainer';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Компании, которые ушли из России</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainContainer>
        <MainBanner />
        <Main />
        <Contacts />
      </MainContainer>
    </div>
  );
};

export default Home;
