export const companiesData = [
  {
    id: 'r1ar12',
    img: '/apple.jpg',
    companie: 'Apple',
    status: 'Полностью',
    category: 'финансы',
  },
  {
    id: 'r1rfwagg11mghm2',
    img: '/apple.jpg',
    companie: 'Ozon',
    status: 'Частично',
    category: 'финансы',
  },
  {
    id: 'r1awfrmgh12',
    img: '/apple.jpg',
    companie: 'Apple',
    status: 'Полностью',
    category: 'финансы',
  },
  {
    id: 'r1r12egmhr12',
    img: '/apple.jpg',
    companie: 'Ozon',
    status: 'Частично',
    category: 'финансы',
  },
  {
    id: 'r1rgesg12mhg',
    img: '/apple.jpg',
    companie: 'Google',
    status: 'Частично',
    category: 'финансы',
  },
  {
    id: 'r14gmhg324r12',
    img: '/apple.jpg',
    companie: 'Apple',
    status: 'Полностью',
    category: 'финансы',
  },
  {
    id: 'r1rdhdmgmhs12',
    img: '/apple.jpg',
    companie: 'Google',
    status: 'Частично',
    category: 'финансы',
  },
  {
    id: 'r1rhdmmgh12',
    img: '/apple.jpg',
    companie: 'Apple',
    status: 'Частично',
    category: 'финансы',
  },
  {
    id: 'r1rmhgmghh12',
    img: '/apple.jpg',
    companie: 'Google',
    status: 'Полностью',
    category: 'финансы',
  },
  {
    id: 'r1fgr1mmum2',
    img: '/apple.jpg',
    companie: 'Apple',
    status: 'Частично',
    category: 'одежда',
  },
  {
    id: 'r1r12awfbgn3',
    img: '/apple.jpg',
    companie: 'Google',
    status: 'Полностью',
    category: 'одежда',
  },
  {
    id: 'r1ffgffar12',
    img: '/apple.jpg',
    companie: 'HP',
    status: 'Частично',
    category: 'одежда',
  },
  {
    id: 'r1r12fwafwa23',
    img: '/apple.jpg',
    companie: 'Google',
    status: 'Полностью',
    category: 'одежда',
  },
  {
    id: 'r1ffgfwfqffqfwqfqafwar12',
    img: '/apple.jpg',
    companie: 'HP',
    status: 'Частично',
    category: 'одежда',
  },
  {
    id: 'r1r12awfwafwa23',
    img: '/apple.jpg',
    companie: 'HP',
    status: 'Полностью',
    category: 'одежда',
  },
  {
    id: 'r1ffgfwwqafwar12',
    img: '/apple.jpg',
    companie: 'HP',
    status: 'Частично',
    category: 'техника',
  },
  {
    id: 'r1r1fawfwafaw223',
    img: '/apple.jpg',
    companie: 'Apple',
    status: 'Полностью',
    category: 'техника',
  },
  {
    id: 'r1ffagewggr12',
    img: '/apple.jpg',
    companie: 'HP',
    status: 'Частично',
    category: 'техника',
  },
  {
    id: 'r1r1fwab223',
    img: '/apple.jpg',
    companie: 'Apple',
    status: 'Полностью',
    category: 'техника',
  },
  {
    id: 'r1ffg2r12',
    img: '/apple.jpg',
    companie: 'HP',
    status: 'Частично',
    category: 'техника',
  },
  {
    id: 'r1rawf1223',
    img: '/apple.jpg',
    companie: 'HP',
    status: 'Полностью',
    category: 'техника',
  },
  {
    id: 'r1ffgffr12',
    img: '/apple.jpg',
    companie: 'Apple',
    status: 'Частично',
    category: 'техника',
  },
];

export const newsData = [
  {
    id: '41affw41',
    source: 'The village',
    title: 'IKEA заявила об уходе из России',
    subtitle:
      'Шведская компания IKEA приостанавливает работу в России и Белоруссии. Об этом сообщила пресс-служба российс....',
    createdAt: '22 часа назад',
    img: '/ikea.jpg',
  },
  {
    id: '41gse41',
    source: 'The village',
    title: 'IKEA заявила об уходе из России',
    subtitle:
      'Шведская компания IKEA приостанавливает работу в России и Белоруссии. Об этом сообщила пресс-служба российс....',
    createdAt: '22 часа назад',
    img: '/ikea.jpg',
  },
  {
    id: '4141gaw',
    source: 'The village',
    title: 'IKEA заявила об уходе из России',
    subtitle:
      'Шведская компания IKEA приостанавливает работу в России и Белоруссии. Об этом сообщила пресс-служба российс....',
    createdAt: '22 часа назад',
    img: '/ikea.jpg',
  },
  {
    id: '41fa41',
    source: 'The village',
    title: 'IKEA заявила об уходе из России',
    subtitle:
      'Шведская компания IKEA приостанавливает работу в России и Белоруссии. Об этом сообщила пресс-служба российс....',
    createdAt: '22 часа назад',
    img: '/ikea.jpg',
  },
];